name: Incremental Build
on:
  push:
    branches:
      - master
      - cheatsheet*
    paths:
      - ./README.md
      - ./artwork/**
      
    paths-ignore:
      - '**/*.yml'  
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.github_token }}
      - name: Generating git log (custom)...
        run: |
          pwd
          ls -lrt
