name: cheatsheet
on:
  push:
    branches:
      - master
      - cheatsheet*
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          repository: ${{ github.repository }}
          token: ${{ secrets.github_token }}
     - name: Convert to pdf format
       shell: bash
       run: |
          pwd
          ls -lrt
          sudo apt install texlive-latex-base
          sudo apt-get install pandoc
          pandoc -r markdown -o GitHubCheatSheet_test.pdf README.md
          
