name: cheatsheet
on:
  push:
    branches:
      - master
      - cheatsheet*
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          repository: ${{ github.repository }}
          token: ${{ secrets.github_token }}
     - name: Convert to pdf format
       shell: bash
       run: |
          pwd
          ls -lrt
          npm install -g md-to-pdf
          md-to-pdf --stylesheet "README.md" > ./GitHubCheatSheet_test.pdf
          
