name: cheatsheet
on:
  push:
    branches:
      - master
      - cheatsheet*
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          repository: ${{ github.repository }}
          token: ${{ secrets.github_token }}
     - name: Convert to pdf format
       shell: bash
       run: |
          pwd
          ls -lrt
          sudo -E apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
          pandoc README.md -o GitHubCheatSheet_test.pdf
          
