name: cheatsheet
on:
  push:
    branches:
      - master
      - cheatsheet*
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          repository: ${{ github.repository }}
          token: ${{ secrets.github_token }}
     - name: Convert to pdf format
       shell: bash
       run: |
          pwd
          ls -lrt
          npm install -g md-to-pdf
          md-to-pdf --stylesheet "README.md" > ./GitHubCheatSheet_test.pdf
          pwd
          ls -lrt
          git config --global hub.protocol https
          git remote set-url --push origin "https://SESA551137:${GITHUB_TOKEN}@github.com/bFO-dev/Platform.git"
          git config --global user.name 'moabu'
          git config --global user.email 'madhavylatha03@gmail.com'
          git branch
          git status
          
