name: cheatsheet
on:
  push:
    branches:
      - master
      - cheatsheet*
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Package Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          repository: ${{ github.repository }}
          token: ${{ secrets.github_token }}
     - name: install libraries
       shell: bash
       run: |
          npm install -g md-to-pdf
          
     - name: Convert to pdf format
       shell: bash
       run: |
          pwd
          ls -lrt          
          cat "README.md" | md-to-pdf  > ./GitHubCheatSheet_test.pdf
          pwd
          ls -lrt
          git config --global hub.protocol https
          git remote set-url --push origin "https://moabu:${github_token}@github.com/moabu/github-cheat-sheet.git"
          git config --global user.name 'moabu'
          git config --global user.email 'madhavylatha03@gmail.com'
          git branch
          git status
          pwd
          git add .
          git commit -m "generated GitHubCheatSheet test pdf file `date`"
          git push origin
         
